### ISSUE TITLE
Epic: Implement backend for Performance Monitoring

### ISSUE THREAD

**Issue by non-binary** [non-binary/bumblebee-alt#105]
### Description: 

Implement backend component.

#### Corresponding Issues

- [ ] Task: Process performance data from Trace and report bad behaviour to Bumblebee team => #103.
- [ ] Task: Implement panel for seeing statuses of Stripe, Zendesk, Big Query, Bitrise, Salesforce, etc => #104.
- [ ] Task: Add unit tests => #9.

### Implemented in: 

TBD.
