### ISSUE TITLE
Epic: 95-100% code coverage

### ISSUE THREAD

**Issue by non-binary** [non-binary/bumblebee-alt#111]
### Description: 

95-100% code coverage.

#### Corresponding Issues

- [ ] Task: Go through source code and determine if any tests were missed => #108.
- [ ] Task: Re-implement broken tests => #109.
- [ ] Task: Implement missing tests => #110.

### Implemented in: 

Swift and Rust in their various components.
