### ISSUE TITLE
Epic: Determine which OP tools Bumblebee will implement

### ISSUE THREAD

**Issue by non-binary** [non-binary/bumblebee-alt#117]
### Description: 

Determine which tools Bumblebee will implement.

#### Corresponding Issues

- [ ] Task: Talk with support and sales team to determine which tools they want => #114.
- [ ] Task: Talk with Optimus Prime team to determine which tools we can implement => #115.
- [ ] Task: Update roadmap to include which tools are going to be implemented => #116.

### Implemented in: 

N/A
