### ISSUE TITLE
2.x Roadmap

### ISSUE THREAD

**Issue by non-binary** [non-binary/bumblebee-alt#118]
This is a roadmap for the 2.x subsequent version of Bumblebee.

**Comment by non-binary** [comment]
- [ ] Milestone: Mac Accessibility.
  - [ ] Epic: User Interface Accessibility.
    - [ ] Task: Add screen reader support.
    - [ ] Task: Add bold text support.
  - [ ] Epic: Keyboard Accessibility.
    - [ ] Task: Add ability to use Bumblebee without a mouse with key shortcuts and bindings.
  - [ ] Epic: Colour Accessibility.
    - [ ] Task: Add differentiation without colour support.
  - [ ] Epic: Add accessibility options to Settings page.
    - [ ] Task: Add options in settings so users can toggle which ones they want on and off.

**Comment by non-binary** [comment]
- [ ] Milestone: Implement Slack text logic.
  - [ ] Epic: Implement Slack text logic => #64.
    - [ ] Task: Implement different strings for different commands => #63.
    - [ ] Task: Write unit tests => #9.

**Comment by non-binary** [comment]
- [ ] Milestone: Implement data source in Slack app.
  - [ ] Epic: Translate work done in the Mac app into Rust => #102.
    - [ ] Task: Rewrite Swift data source code in Rust => #101.
    - [ ] Task: Write unit tests => #9.
