### ISSUE TITLE
2.0 Roadmap - Revision 1

### ISSUE THREAD

**Issue by non-binary** [non-binary/bumblebee-alt#29]
This is a roadmap for the 2.0 version of Bumblebee. The roadmap consists of milestones which is a group of epics that contain a list of tasks. The current estimate is mid February 2021 to commence beta testing and end of February for soft launch of the 2.0 version of the app.

### Milestones

- [x] November 6th, 2020: [A: Setup](https://github.com/bitrise-io/bumblebee/milestone/1). :tada:
- [ ] November 20th, 2020: [B: Mac + User Interface](https://github.com/bitrise-io/bumblebee/milestone/2).
- [ ] ~~November 27th, 2020: [C: Slack + Text Logic](https://github.com/bitrise-io/bumblebee/milestone/3).~~
- [ ] December 18th, 2020: [D: SSO](https://github.com/bitrise-io/bumblebee/milestone/4).
- [ ] January 1st, 2021: [E: Deep Linking](https://github.com/bitrise-io/bumblebee/milestone/5).
- [ ] January 15th, 2021: [F: Mac + Data Source](https://github.com/bitrise-io/bumblebee/milestone/6).
- [ ] ~~January 22nd, 2021: [G: Slack + Data Source](https://github.com/bitrise-io/bumblebee/milestone/7).~~
- [ ] January 29th, 2021: [H: Mac + Performance Monitoring](https://github.com/bitrise-io/bumblebee/milestone/8).
- [ ] February 12th, 2021: [I: Unit + UI Tests](https://github.com/bitrise-io/bumblebee/milestone/9).
- [ ] February 26th, 2021: [J: Mac + Optimus Prime](https://github.com/bitrise-io/bumblebee/milestone/10).
- [ ] April 1st, 2021: [K: Documentation](https://github.com/bitrise-io/bumblebee/milestone/11).

### Loose Leaf Tasks

- [x] Talk to Katie to determine how much time Luna (me) can spend on Bumblebee.
- [x] Ask Simon to rename Heroku application br-bumblebee-auth to br-bumblebee-backend.

**Comment by non-binary** [comment]
- [x] **Milestone: Setting up the projects and scaffolding => [milestone#1](https://github.com/bitrise-io/bumblebee/milestone/1). Deadline: Nov 6th, 2020.**
  - [x] Epic: Getting Started => #7.
    - [x] Task: Choose UI framework => #3.
    - [x] Task: Choose architecture => #4.
    - [x] Task: Create starter projects => #5.
    - [x] Task: Create Bitrise projects and their workflows => #6.
  - [x] Epic: Setup Viper and Trace => #18.
    - [x] Task: Setup Viper => #28.
    - [x] Task: Setup Trace SDK => #22.
  - [ ] Epic: Add Rust scaffolding => #32.
    - [ ] Task: Create scaffolding for Slack application => #30.
    - [ ] Task: Create scaffolding for Backend application => #31.

**Comment by non-binary** [comment]
- [ ] **Milestone: Implement Mac user interface => [milestone#2](https://github.com/bitrise-io/bumblebee/milestone/2). Deadline: November 20th, 2020.**
  - [ ] Epic: Mock data structures => #33.
    - [ ] Task: Add User and Organization data structures => #34.
    - [ ] Task: Add App data structure => #35.
    - [ ] Task: Add Build data structure => #36.
    - [ ] Task: Add Zendesk data structure => #37.
    - [ ] Task: Add Stripe data structure => #38.
    - [ ] Task: Add Bumblebee User data structure => #39.
    - [ ] Task: Add remaining enums and related structs for UI building => #40.
  - [ ] Epic: Add Sidebar UI and auth page => #51.
    - [ ] Task: Add Auth UI => #41.
    - [ ] Task: Add Accounts UI => #42.
    - [ ] Task: Add Apps UI => #43.
    - [ ] Task: Add Builds UI => #44.
    - [ ] Task: Add Zendesk UI => #45.
    - [ ] Task: Add Stripe UI => #46.
    - [ ] Task: Add splash page for Optimus Prime UI => #47.
    - [ ] Task: Add Manage Access UI => #48.
    - [ ] Task: Add Performance UI => #49.
    - [ ] Task: Add Settings UI => #50.
  - [ ] Epic: Add Accounts tab bar UI => #57.
    - [ ] Task: Add Summary tab UI => #52.
    - [ ] Task: Add Apps tab UI => #53.
    - [ ] Task: Add Associations tab UI => #54.
    - [ ] Task: Add Zendesk tab UI => #55.
    - [ ] Task: Add Stripe tab UI => #56.
  - [ ] Epic: Add fake data and test UI => #60.
    - [ ] Task: Add fake data to test UI => #58.
    - [ ] Task: Thoroughly test UI to confirm everything is working => #59.
    - [ ] Task: Share build with beta testers to click around to ensure everything is the way it should be => #60.
  - [ ] Epic: Add UI and Unit tests for user interface => #62.
    - [ ] Task: Add UI tests => #10.
    - [ ] Task: Add unit tests => #9.
    - [ ] Task: Configure Bitrise to run UI and Unit tests in builds => #61.

**Comment by non-binary** [comment]
- [ ] **Milestone: Implement Slack text logic => [milestone#3](https://github.com/bitrise-io/bumblebee/milestone/3). Deadline: November 27th, 2020.** 
  - [ ] Epic: Implement Slack text logic => #64.
    - [ ] Task: Implement different strings for different commands => #63.
    - [ ] Task: Write unit tests => #9.

**Comment by non-binary** [comment]
- [ ] **Milestone: Implement SSO => [milestone#4](https://github.com/bitrise-io/bumblebee/milestone/4). Deadline: December 18th, 2020.**
   - [ ] Epic: Implement Backend component => #67.
     - [ ] Task: Research Google SSO and how to implement it in Rust => #65.
     - [ ] Task: Implement backend component in Rust => #66.
     - [ ] Task: Write unit tests => #9.
   - [ ] Epic: Implement Frontend/Mac component => #70.
     - [ ] Task: Research Google SSO and how to implement it in the front-end => #68.
     - [ ] Task: Implement frontend component in Swift => #69.
     - [ ] Task: Write unit tests => #9.
     - [ ] Task: Write UI tests => #10.
  - [ ] Epic: Implement access control management => #77.
    - [ ] Task: Implement backend component to store active users => #71.
    - [ ] Task: Implement frontend component to show active users => #72.
    - [ ] Task: Implement ability to add new users => #73.
    - [ ] Task: Implement ability to remove existing users => #74.
    - [ ] Task: Implement sessions so when a user is removed, they can no longer use the app => #75.
    - [ ] Task: Implement kill switch to remove all users access => #76.

**Comment by non-binary** [comment]
- [ ] **Milestone: Implement deep linking => [milestone#5](https://github.com/bitrise-io/bumblebee/milestone/5). Deadline: January 1st, 2021.**
  - [ ] Epic: Implement deep link URL schemes => #79.
    - [ ] Task: Implement deep links for each page in the UI with data fields => #78.
    - [ ] Task: Write unit tests => #9.

**Comment by non-binary** [comment]
- [ ] **Milestone: Implement data source in Mac app => [milestone#6](https://github.com/bitrise-io/bumblebee/milestone/6). Deadline: January 15th, 2021.**
  - [ ] Epic: Implement infrastructure to pull data from Bitrise production database => #82.
    - [ ] Task: Implement ability to pull apps from database => #80.
    - [ ] Task: Implement ability to pull builds from database => #81.
    - [ ] Task: Write unit tests => #9.
  - [ ] Epic: Implement Zendesk data source => #85.
    - [ ] Task: Implement ability to pull Zendesk tickets by ID => #83.
    - [ ] Task: Implement ability to pull Zendesk tickets by email address. => #84.
    - [ ] Task: Write unit tests => #9.
  - [ ] Epic: Implement Stripe data source => #88.
    - [ ] Task: Implement ability to pull Stripe data by `cus_` ID => #86.
    - [ ] Task: Implement ability to pull Stripe data by email address => #87.
    - [ ] Task: Write unit tests => #9.
  - [ ] Epic: Implement Accounts data source => #92.
    - [ ] Task: Implement ability to search users and organizations through Big Query => #89.
    - [ ] Task: Pull account's apps from Bitrise database => #90.
    - [ ] Task: Pull account's app's builds from Bitrise database => #91.
    - [ ] Task: Write unit tests => #9.
  - [ ] Epic: Implement individual apps search => #94.
    - [ ] Task: Implement the ability to search for apps by app slug => #93.
    - [ ] Task: Write unit tests => #9.
  - [ ] Epic: Implement individual builds search => #96.
    - [ ] Task: Implement the ability to search for builds by build slug => #95.
    - [ ] Task: Write unit tests => #9.
  - [ ] Epic: Implement individual Zendesk search.
    - [ ] Task: Implement the ability to search for Zendesk tickets by ID => #97 and #83.
    - [ ] Task: Implement the ability to search for Zendesk tickets by email => #98 and #84.
    - [ ] Task: Write unit tests => #9.
  - [ ] Epic: Implement individual Stripe search => #100.
    - [ ] Task: Implement the ability to search for customers by `cus_` ID => #86.
    - [ ] Task: Write unit tests => #9.

**Comment by non-binary** [comment]
- [ ] **Milestone: Implement data source in Slack app => [milestone#7](https://github.com/bitrise-io/bumblebee/milestone/7). Deadline: January 22nd, 2021.**
  - [ ] Epic: Translate work done in the Mac app into Rust.
    - [ ] Task: Rewrite the Swift code in Rust so it can be used by the Slack application.
    - [ ] Task: Write unit tests => #9.

**Comment by non-binary** [comment]
- [ ] Milestone: Performance Monitoring.
  - [ ] Epic: Implement backend component.
    - [ ] Task: Process performance data from Trace and report bad behaviour to Bumblebee team.
    - [ ] Task: Implement panel for seeing statuses of Stripe, Zendesk, Big Query, Bitrise, Salesforce, etc.
    - [ ] Task: Add unit tests => #9.
  - [ ] Epic: Implement Mac component.
    - [ ] Task: Implement UI.
    - [ ] Task: Add UI tests => #10.

**Comment by non-binary** [comment]
- [ ] Milestone: Unit and UI testing.
  - [ ] Epic: 95-100% code coverage.
    - [ ] Task: Go through source code and determine if any tests were missed.
    - [ ] Task: Re-implement broken tests.
    - [ ] Task: Implement missing tests.
  - [ ] Epic: Optimize Bitrise for best build times.
    - [ ] Task: Work with infrastructure team and tooling team to optimize builds.

**Comment by non-binary** [comment]
- [ ] Milestone: Optimus Prime.
  - [ ] Epic: Determine which tools Bumblebee will implement.
    - [ ] Task: Talk with support and sales team to determine which tools they want.
    - [ ] Task: Talk with Optimus Prime team to determine which tools we can implement.
    - [ ] Task: Update roadmap to include which tools are going to be implemented.
  - [ ] Epic: Implement UI.
    - [ ] Task: TBD but implement UI for each tool we are OP implementing in Bumblebee.
    - [ ] Task: Implement UI tests => #10.
  - [ ] Epic: Implement functionality.
    - [ ] Task: Implement OP tools in Bumblebee by communicating with OP server component.
    - [ ] Task: Write unit tests => #9.
  - [ ] Epic: Implement event logging.
    - [ ] Task: Implement event logging for Optimus Prime tools so administrators can see who has done what.
    - [ ] Task: Implement UI for this to see behaviour.

**Comment by non-binary** [comment]
- [ ] Milestone: Mac Accessibility.
  - [ ] Epic: User Interface Accessibility.
    - [ ] Task: Add screen reader support.
    - [ ] Task: Add bold text support.
  - [ ] Epic: Keyboard Accessibility.
    - [ ] Task: Add ability to use Bumblebee without a mouse with key shortcuts and bindings.
  - [ ] Epic: Colour Accessibility.
    - [ ] Task: Add differentiation without colour support.
  - [ ] Epic: Add accessibility options to Settings page.
    - [ ] Task: Add options in settings so users can toggle which ones they want on and off.

**Comment by non-binary** [comment]
- [ ] Milestone: Documentation.
  - [ ] Epic: Write documentation for Mac application.
    - [ ] Task: Plan out documentation pages.
    - [ ] Task: Write documentation.
  - [ ] Epic: Write documentation for Slack application.
    - [ ] Task: Plan out documentation pages.
    - [ ] Task: Write documentation.
