### ISSUE TITLE
Epic: Add mock data structures

### ISSUE THREAD

**Issue by non-binary** [non-binary/bumblebee-alt#33]
### Description: 

Create the necessary data structures to get started with the user interface.

- [ ] Add User and Organization data structures => #34.
- [ ] Add App data structure => #35.
- [ ] Add Build data structure => #36.
- [ ] Add Zendesk data structure => #37.
- [ ] Add Stripe data structure => #38.
- [ ] Add Bumblebee User data structure => #39.
- [ ] Add remaining enums and related structs for UI building => #40.

### Implemented in: 

This will be implemented in Swift in the Mac component.
