### ISSUE TITLE
Epic: Add Sidebar UI and auth page

### ISSUE THREAD

**Issue by non-binary** [non-binary/bumblebee-alt#51]
### Description: 

Add Sidebar UI and auth page.

#### Corresponding Issues

- [x] Task: Add Auth UI => #41. Implemented in #127.
- [ ] Task: Add Accounts UI => #42.
- [ ] Task: Add Apps UI => #43.
- [ ] Task: Add Builds UI => #44.
- [ ] Task: Add Zendesk UI => #45.
- [ ] Task: Add Stripe UI => #46.
- [ ] Task: Add splash page for Optimus Prime UI => #47.
- [ ] Task: Add Manage Access UI => #48.
- [ ] Task: Add Performance UI => #49.
- [ ] Task: Add Settings UI => #50.

### Implemented in: 

Swift in the Mac component.

**Comment by non-binary** [comment]
https://fivestars.blog/code/ios-dark-mode-how-to.html
