### ISSUE TITLE
Epic: Add Accounts tab bar UI

### ISSUE THREAD

**Issue by non-binary** [non-binary/bumblebee-alt#57]
### Description: 

Add Accounts tab bar UI.

#### Corresponding Issues

- [ ] Task: Add Summary tab UI => #52.
- [ ] Task: Add Apps tab UI => #53.
- [ ] Task: Add Associations tab UI => #54.
- [ ] Task: Add Zendesk tab UI => #55.
- [ ] Task: Add Stripe tab UI => #56.

### Implemented in: 

Swift in the Mac component.
