### ISSUE TITLE
Epic: Add fake data and test UI

### ISSUE THREAD

**Issue by non-binary** [non-binary/bumblebee-alt#60]
### Description: 

Add fake data and test UI.

#### Corresponding Issues

- [ ] Task: Add fake data to test UI => #58.
- [ ] Task: Thoroughly test UI to confirm everything is working => #59.
- [ ] Task: Share build with beta testers to click around to ensure everything is the way it should be => #60.

### Implemented in: 

Swift in the Mac component.
