### ISSUE TITLE
Epic: Add UI and Unit tests for user interface

### ISSUE THREAD

**Issue by non-binary** [non-binary/bumblebee-alt#62]
### Description: 

Add UI and Unit tests for user interface.

#### Corresponding Issues

- [ ] Task: Add UI tests => #10.
- [ ] Task: Add unit tests => #9.
- [ ] Task: Configure Bitrise to run UI and Unit tests in builds => #61.

### Implemented in: 

Swift in the Mac component.
