### ISSUE TITLE
Epic: Implement Backend SSO component

### ISSUE THREAD

**Issue by non-binary** [non-binary/bumblebee-alt#67]
### Description: 

Implement Backend component.

#### Corresponding Issues

- [ ] Task: Research Google SSO and how to implement it in Rust => #65.
- [ ] Task: Implement backend component in Rust => #66.
- [ ] Task: Write unit tests => #9.

### Implemented in: 

Rust in the Backend component.
