### ISSUE TITLE
Epic: Implement Frontend/Mac SSO component

### ISSUE THREAD

**Issue by non-binary** [non-binary/bumblebee-alt#70]
### Description: 

Implement Frontend/Mac SSO component.

#### Corresponding Issues

- [ ] Task: Research Google SSO and how to implement it in the front-end => #68.
- [ ] Task: Implement frontend component in Swift => #69.
- [ ] Task: Write unit tests => #9.
- [ ] Task: Write UI tests => #10.

### Implemented in: 

Swift in the Mac component.
