### ISSUE TITLE
Epic: Implement access control management

### ISSUE THREAD

**Issue by non-binary** [non-binary/bumblebee-alt#77]
### Description: 

Implement access control management.

#### Corresponding Issues

- [ ] Task: Implement backend component to store active users => #71.
- [ ] Task: Implement frontend component to show active users => #72.
- [ ] Task: Implement ability to add new users => #73.
- [ ] Task: Implement ability to remove existing users => #74.
- [ ] Task: Implement sessions so when a user is removed, they can no longer use the app => #75.
- [ ] Task: Implement kill switch to remove all users access => #76.

### Implemented in: 

Both Swift in Mac component and Rust in Backend component.
