### ISSUE TITLE
Epic: Implement infra to pull data from Bitrise prod db

### ISSUE THREAD

**Issue by non-binary** [non-binary/bumblebee-alt#82]
### Description: 

Implement infrastructure to pull data from Bitrise production database.

#### Corresponding Issues

- [ ] Task: Implement ability to pull apps from database => #80.
- [ ] Task: Implement ability to pull builds from database => #81.
- [ ] Task: Write unit tests => #9.

### Implemented in: 

Swift in the Mac app.
