### ISSUE TITLE
Epic: Implement Zendesk data source

### ISSUE THREAD

**Issue by non-binary** [non-binary/bumblebee-alt#85]
### Description: 

Implement Zendesk data source.

#### Corresponding Issues

- [ ] Task: Implement ability to pull Zendesk tickets by ID => #83.
- [ ] Task: Implement ability to pull Zendesk tickets by email address. => #84.
- [ ] Task: Write unit tests => #9.

### Implemented in: 

Swift in the Mac app.
