### ISSUE TITLE
Epic: Implement Stripe data source

### ISSUE THREAD

**Issue by non-binary** [non-binary/bumblebee-alt#88]
### Description: 

Implement Stripe data source.

#### Corresponding Issues

- [ ] Task: Implement ability to pull Stripe data by `cus_` ID => #86.
- [ ] Task: Implement ability to pull Stripe data by email address => #87.
- [ ] Task: Write unit tests => #9.

### Implemented in: 

Swift in the Mac app.
