### ISSUE TITLE
Epic: Implement Accounts data source

### ISSUE THREAD

**Issue by non-binary** [non-binary/bumblebee-alt#92]
### Description: 

Implement Accounts data source.

#### Corresponding Issues

- [ ] Task: Implement ability to search users and organizations through Big Query => #89.
- [ ] Task: Pull account's apps from Bitrise database => #90.
- [ ] Task: Pull account's app's builds from Bitrise database => #91.
- [ ] Task: Write unit tests => #9.

### Implemented in: 

Swift.
