### ISSUE TITLE
Epic: Implement individual Zendesk search

### ISSUE THREAD

**Issue by non-binary** [non-binary/bumblebee-alt#99]
### Description: 

Implement individual Zendesk search.

#### Corresponding Issues

- [ ] Task: Implement the ability to search for Zendesk tickets by ID => #97.
- [ ] Task: Implement the ability to search for Zendesk tickets by email => #98.
- [ ] Task: Write unit tests => #9.

### Implemented in: 

Swift.
